- restore -t/--configtest flag accidentally removed in the previous released (LOGSTASH-1279)
Testing -
  % bin/logstash agent -e '' --configtest
  Configuration OK

  % bin/logstash agent -e 'asdf' --configtest
  Error: Expected one of #, input, filter, output at line 1, column 1
  (byte 1) after


Former-commit-id: 09bf65cd6138549b5a71d18e2fc701d340643d67