Not all irc messages have a user / nickname
Blows up with:

Restarting input due to exception {:plugin=><LogStash::Inputs::Irc
    nick=>"logstash_fr", channels=>["#fr"], charset=>"UTF-8",
        host=>"localhost", type=>"irc", user=>"logstash",
        real=>"logstash">, :level=>:error}
        Input thread exception {:plugin=><LogStash::Inputs::Irc
            nick=>"logstash_infra", channels=>["#infra"],
                charset=>"UTF-8", host=>"localhost", type=>"irc",
                user=>"logstash", real=>"logstash">,
                :exception=>#<NoMethodError: undefined method `nick' for
                    nil:NilClass>,
                :backtrace=>["file:/opt/logstash-monolithic.jar!/logstash/inputs/irc.rb:77:in
                    `run'", "org/jruby/RubyKernel.java:1409:in `loop'",
                "file:/opt/logstash-monolithic.jar!/logstash/inputs/irc.rb:73:in
                    `run'",
                "file:/opt/logstash-monolithic.jar!/logstash/agent.rb:761:in
                    `run_input'",
                "file:/opt/logstash-monolithic.jar!/logstash/agent.rb:407:in
                    `start_input'"], :level=>:warn}


Former-commit-id: fa3e503935780de75127ca6616dc2c6d5cd48142